DROP TABLE IF EXISTS MEMBER CASCADE;
CREATE TABLE `MEMBER` (
	`MEMBER_ID`         BIGINT          NOT NULL    AUTO_INCREMENT,
	`MEMBER_EMAIL`      VARCHAR(50)     NOT NULL,
	`MEMBER_PWD`        VARCHAR(100)	NOT NULL,
	`MEMBER_NM`         VARCHAR(50)     NOT NULL,
	`MEMBER_REGDATE`    TIMESTAMP	    NOT NULL,
    PRIMARY KEY (MEMBER_ID)
);

DROP TABLE IF EXISTS MEMBER_AUTHORITY CASCADE;
CREATE TABLE `MEMBER_AUTHORITY` (
    `AUTHORITY_ID`	    BIGINT	        NOT NULL    AUTO_INCREMENT,
    `MEMBER_ID`         BIGINT	        NOT NULL,
    `AUTHORITY_ROLE`    VARCHAR(20)     NOT NULL,
    PRIMARY KEY (AUTHORITY_ID),
    FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER (MEMBER_ID) ON DELETE CASCADE
);