spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mysql://localhost:3306/96talk
    username: root
    password: ikavon321
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: testuser
      password: asdqwe123
      database: 96talk

# JWT Secret Key
custom:
  jwt-access-secret-key: accessSecretKey

# file
file:
  dir: F:/test-file/