spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:tcp://localhost/~/96talk;
    username: sa
    password: 123123
  redis:
    host: localhost
    port: 6379
  data:
    mongodb:
      host: localhost
      port: 27017
      authentication-database: admin
      username: testuser
      password: asdqwe123
      database: 96talk

# JWT Secret Key
custom:
  jwt-access-secret-key: accessSecretKey

# file
file:
  dir: F:/test-file/